// <auto-generated />
namespace MyEShop.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Temp03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Temp03));
        
        string IMigrationMetadata.Id
        {
            get { return "201704250821197_Temp03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
